//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsuming.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IDTEService")]
    public interface IDTEService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTEService/GetCustomer", ReplyAction="http://tempuri.org/IDTEService/GetCustomerResponse")]
        string GetCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTEService/GetCustomer", ReplyAction="http://tempuri.org/IDTEService/GetCustomerResponse")]
        System.Threading.Tasks.Task<string> GetCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTEService/UpdateCustomer", ReplyAction="http://tempuri.org/IDTEService/UpdateCustomerResponse")]
        string UpdateCustomer(string Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTEService/UpdateCustomer", ReplyAction="http://tempuri.org/IDTEService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<string> UpdateCustomerAsync(string Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTEService/GetToken", ReplyAction="http://tempuri.org/IDTEService/GetTokenResponse")]
        string GetToken(string Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTEService/GetToken", ReplyAction="http://tempuri.org/IDTEService/GetTokenResponse")]
        System.Threading.Tasks.Task<string> GetTokenAsync(string Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTEService/GetMessage", ReplyAction="http://tempuri.org/IDTEService/GetMessageResponse")]
        string GetMessage(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTEService/GetMessage", ReplyAction="http://tempuri.org/IDTEService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDTEServiceChannel : WCFConsuming.WCFService.IDTEService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DTEServiceClient : System.ServiceModel.ClientBase<WCFConsuming.WCFService.IDTEService>, WCFConsuming.WCFService.IDTEService {
        
        public DTEServiceClient() {
        }
        
        public DTEServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DTEServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DTEServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DTEServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCustomer() {
            return base.Channel.GetCustomer();
        }
        
        public System.Threading.Tasks.Task<string> GetCustomerAsync() {
            return base.Channel.GetCustomerAsync();
        }
        
        public string UpdateCustomer(string Request) {
            return base.Channel.UpdateCustomer(Request);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCustomerAsync(string Request) {
            return base.Channel.UpdateCustomerAsync(Request);
        }
        
        public string GetToken(string Request) {
            return base.Channel.GetToken(Request);
        }
        
        public System.Threading.Tasks.Task<string> GetTokenAsync(string Request) {
            return base.Channel.GetTokenAsync(Request);
        }
        
        public string GetMessage(string Name) {
            return base.Channel.GetMessage(Name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string Name) {
            return base.Channel.GetMessageAsync(Name);
        }
    }
}
