//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsuming.WcfServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceProxy")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceProxy.IServiceProxy")]
    public interface IServiceProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/GetMessage", ReplyAction="http://tempuri.org/IServiceProxy/GetMessageResponse")]
        string GetMessage(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/GetMessage", ReplyAction="http://tempuri.org/IServiceProxy/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceProxy/GetDataUsingDataContractResponse")]
        WCFConsuming.WcfServiceProxy.CompositeType GetDataUsingDataContract(WCFConsuming.WcfServiceProxy.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceProxy/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCFConsuming.WcfServiceProxy.CompositeType> GetDataUsingDataContractAsync(WCFConsuming.WcfServiceProxy.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/GetToken", ReplyAction="http://tempuri.org/IServiceProxy/GetTokenResponse")]
        string GetToken(string Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/GetToken", ReplyAction="http://tempuri.org/IServiceProxy/GetTokenResponse")]
        System.Threading.Tasks.Task<string> GetTokenAsync(string Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProxyChannel : WCFConsuming.WcfServiceProxy.IServiceProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProxyClient : System.ServiceModel.ClientBase<WCFConsuming.WcfServiceProxy.IServiceProxy>, WCFConsuming.WcfServiceProxy.IServiceProxy {
        
        public ServiceProxyClient() {
        }
        
        public ServiceProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string value) {
            return base.Channel.GetMessage(value);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string value) {
            return base.Channel.GetMessageAsync(value);
        }
        
        public WCFConsuming.WcfServiceProxy.CompositeType GetDataUsingDataContract(WCFConsuming.WcfServiceProxy.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WCFConsuming.WcfServiceProxy.CompositeType> GetDataUsingDataContractAsync(WCFConsuming.WcfServiceProxy.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetToken(string Request) {
            return base.Channel.GetToken(Request);
        }
        
        public System.Threading.Tasks.Task<string> GetTokenAsync(string Request) {
            return base.Channel.GetTokenAsync(Request);
        }
    }
}
